#!/usr/bin/env python3
import pyvisa as visa
import sys
import time

rm = visa.ResourceManager()

name = rm.list_resources()[0]

inst = rm.open_resource(name)

inst.baud_rate = 38400
inst.timeout = None

if __name__ == '__main__':
    for line in sys.stdin:
        if line.lower().startswith('#read'):
            print(inst.read(), file = sys.stdout)
            continue
        if line.startswith('#'):
            continue
        inst.write(line)

